name: Build and Upload Deb Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Procursus
      uses: dhinakg/procursus-action@main
      with:
        packages: findutils sed coreutils

    - name: Set up Theos
      run: |
        brew install dpkg
        export BASEDIR="$(pwd)"
        export THEOS="${BASEDIR}/theos"
        mkdir -p $THEOS
        curl -fsSLO https://raw.githubusercontent.com/theos/theos/master/bin/install-theos
        chmod +x install-theos
        gsed -E "/^\s*get_theos\s*$/,+1 s/^(\s*)(get_sdks)\s*$/\1mkdir -p \${THEOS}\/sdks\n\1touch \${THEOS}\/sdks\/sdk\n\1\2/g" -i install-theos
        bash install-theos
        curl -L https://github.com/theos/sdks/releases/latest/download/iPhoneOS16.5.sdk.tar.xz --output $THEOS/sdks/iPhoneOS16.5.sdk.tar.xz
        gunzip $THEOS/sdks/iPhoneOS16.5.sdk.tar.xz
        tar -xf $THEOS/sdks/iPhoneOS16.5.sdk.tar -C $THEOS/sdks
        rm $THEOS/sdks/iPhoneOS16.5.sdk.tar
        cd $BASEDIR

    - name: Build rooted package
      run: |
        export BASEDIR="$(pwd)"
        export THEOS="${BASEDIR}/theos"
        make clean
        make package

    - name: Upload rooted package
      uses: actions/upload-artifact@v4
      with:
        name: ZeroTieriOSFix.deb
        path: ./packages/*.deb

    - name: Build rootless package
      run: |
        export BASEDIR="$(pwd)"
        export THEOS="${BASEDIR}/theos"
        make clean
        THEOS_PACKAGE_SCHEME=rootless make package

    - name: Upload rootless package
      uses: actions/upload-artifact@v4
      with:
        name: ZeroTieriOSFix-rootless.deb
        path: ./packages/*.deb